name: GA Testing

on: workflow_dispatch

jobs:
  inspect-env:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo GitHub context info
        run: |
          echo "Username is ${{ github.actor }}"
          echo "Runner OS is ${{ runner.os }}"
          echo "Repository name is ${{ github.repository }}"
          echo "Action Repository is ${{ github.action_repository }}"
          echo "Event ${{ github.event_name }} triggered the workflow"

      - name: Display versions of preinstalled software
        run: |
          echo "Displaying software versions"
          echo "git: $(git --version)"
          echo "docker: $(docker --version || echo 'Docker not installed')"
          echo "gradle: $(gradle --version | head -n1 || echo 'Gradle not installed')"
          echo "java: $(java -version 2>&1 | head -n1)"

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Show directory tree up to 2 levels
        run: tree -L 2 || echo "tree command failed"

      - name: Ensure key files exist and initialize README if missing
        run: |
          if [ -f README.md ]; then
            echo "✅ README.md exists"
          else
            echo "⚠️ README.md missing — creating one now..."
            cat <<EOF > README.md
            This directory has been initialized as a Kotlin-based project to explore and test the capabilities of GitHub Actions CI workflows. The purpose is to demonstrate how automation can assist in project quality, build consistency, and environment introspection.
            This README was automatically generated by a GitHub Actions workflow.
            EOF
            echo "✅ README.md created with default content."
          fi

          if [ -d src ]; then
          echo "✅ src/ directory exists"
          else
          echo "⚠️ src/ directory is missing"
          fi
