name: runner_structure.yml
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main

jobs:
  runner_info:
    runs-on: ubuntu-latest
    outputs:
      pwd_pre_checkout: ${{ steps.pre.outputs.first }}
      pwd_post_checkout: ${{ steps.post.outputs.second }}
    steps:
      - name: pre_checkout_pwd
        id: pre
        run: echo "first=$(pwd)" >> $GITHUB_OUTPUT

      - name: checkout
        uses: actions/checkout@v3

      - name: post_checkout_pwd
        id: post
        run: echo "second=$(pwd)" >> $GITHUB_OUTPUT

  getting_info:
    needs: runner_info
    runs-on: ubuntu-latest
    steps:
      - name: Fetching pre pwd info from last job
        run: echo "Pre -- ${{ needs.runner_info.outputs.pwd_pre_checkout }}"

      - name: Fetching post data from last job
        run: echo "Post -- ${{ needs.runner_info.outputs.pwd_post_checkout }}"