name: sequential-jobs
on:
  push:
    branches:
      - main

jobs:
  first:
    outputs:
      calculated_conatiner_version: ${{ steps.container_version.outputs.docker_version }}
    runs-on: ubuntu-latest
    steps:
      - name: "Listing some data"
        id: container_version
        run: |
          echo "The java version is"
          echo "docker_version=$(docker -v)" >> $GITHUB_OUTPUT

  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: "Reading output of previous job"
        env:
          CALCULATED_JAVA_VERSION: ${{ needs.first.outputs.calculated_container_version }}
        run: |
          echo "Calculated java version from last step -> $CALCULATED_JAVA_VERSION"
