name: sequential-jobs
#on:
#  push:
#    branches:
#      - main

on:
  workflow_dispatch:

jobs:
  first:
    outputs:
      calculated_container_version: ${{ steps.container_version.outputs.docker_version }}
    runs-on: ubuntu-latest
    steps:
      - name: "Listing some data"
        id: container_version
        run: |
          echo "The docker version is"
          echo docker -v 
          echo "docker_version=$(docker -v)" >> $GITHUB_OUTPUT

  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: "Reading output of previous job"
        env:
          CALCULATED_DOCKER_VERSION: ${{ needs.first.outputs.calculated_container_version }}
        run: |
          echo "Calculated docker version from last step -> $CALCULATED_DOCKER_VERSION"
