name: Workspaces

on:
  workflow_dispatch:

#  push:
#    branches: [ main, dev ]

jobs:
  workspace-info:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo runner workspace via shell env
        run: |
          echo "Workspace-info job -> GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          echo "Workspace-info job -> github.workspace (expression) is ${{ github.workspace }}"
  job-a:
    runs-on: ubuntu-22.04
    steps:
      - name: Github And Runner Workspace for job-a
        run: |
          echo "Job A -> GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          echo "Job A -> github.workspace (expression) is ${{ github.workspace }}"
  job-b:
    runs-on: ubuntu-22.04
    steps:
      - name: Github And Runner Workspace for job-b
        run: |
          echo "Job B -> GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          echo "Job B -> github.workspace (expression) is ${{ github.workspace }}"
  final:
    runs-on: ubuntu-22.04
    steps:
      - name: Pre-checkout in final job
        run: |
          echo "Final job pre-checkout -> GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          echo "Final job pre-checkout -> github.workspace (expression) is ${{ github.workspace }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Post-checkout in final job
        run: |
          echo "Final job post-checkout -> GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          echo "Final job post-checkout -> github.workspace (expression) is ${{ github.workspace }}"
