name: workspace-contents
on:
  push:
    branches:
      - main

jobs:
  github-workspace-contents:
    runs-on: ubuntu-latest
    steps:
      - name: Contents of github workspace pre-checkout
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Contents pre-checkout:"
          ls -la "$GITHUB_WORKSPACE" || echo "(likely empty or not yet checked out)"
      - name: Perform Checkout
        uses: actions/checkout@v3
      - name: Contents of github workspace post-checkout
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Contents post-checkout:"
          ls -la "$GITHUB_WORKSPACE"

  getting-current-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Getting current directory pre checkout
        run: |
          echo "Current directory: $(pwd)"
          echo "And items in this directory are ->"
          ls -l 
      - name: Do Checkout
        uses: actions/checkout@v3
      - name: Getting current directory post checkout
        run: |
          echo "Now the current directory is $(pwd)"
          echo "And the items in this directory are ->"
          ls -l 
